// on clicking *any* p tag, change the font of that one p tag to comic sans
// use this for the font family: "Comic Sans MS", cursive, sans-serif
// HINT: you might need to loop over all the p tags somehow...